name: My-GitHubActionsFeature
on: 
  push:
    branches:
      - 'feature**'
  pull_request:
      branches: 
      - 'develop'
  workflow_dispatch:
  
jobs:
  unit_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.3
      
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Maven Test
        run: mvn -B clean test
        
      - name: Run a multi-line script
        run: echo unit test completed
        
  integration_testing:
    if: github.ref == 'refs/heads/develop'
    needs: unit_testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.3
    
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Maven Test
        run: mvn -B clean integration-test
        
      - name: Run a multi-line script
        run: echo Integration test completed
  packaging:
    runs-on: ubuntu-latest
    needs: [unit_testing,integration_testing]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.3
      - name: build and start database container
        run: docker-compose up -d  
        
      - name: Package maven
        run: echo Hello, world form deploy!
   
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
