name: My-GitHubActions

on: 
  push:
    branches: 
      -develop
      
  workflow_dispatch:
  
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.3
        
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Maven Test
        run: mvn -B clean test
        
      - name: Run a multi-line script
        run: Test completed
  packaging:
    runs-on: ubuntu-latest
    needs: [testing]
    steps:
      - name: Print hello message
        run: echo Hello, world form deploy!
      - name: build and start database container
        run: docker-compose -f docker-compose.yml --build

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
